### ISSUE TITLE
Create "stub" software library

### ISSUE THREAD

**Issue by CarlosLopezGit** [salamando15/TileBot#13]
Create a TileBot.py stub software library. Determine necessary functions for the robot to operate. Define the functions and the inputs of the functions and write `pass` inside for now

- [x] Include info() function.
- [x] Add functions for color sensor
- [x] Add functions for robot movement
- [x] Add functions for pi camera

Refer to the "organizing software slides" and "Deliverable: Github repository - using Git" pages 8-11 on the class brightspace for guidance

**Comment by salamando15** [comment]
-added movement functions

**Comment by CarlosLopezGit** [comment]
Added color sensor and pi camera stub functions

**Comment by CarlosLopezGit** [comment]
Reviewed and verified at team meeting 3/1/23
