### ISSUE TITLE
Set up project repository

### ISSUE THREAD

**Issue by salamando15** [salamando15/TileBot#2]
- [x] Create repo
- [x] Add collaborators
- [x] Set up milestones
- [x]  Set up labels
- [x] Associate with project

**Comment by CarlosLopezGit** [comment]
Labels used:
bug - something isn't working as expected
design - sketches, schematics, etc.
documentation - improvements or additions to documentation
easy - simple task
enhancement - new feature or request or request
hard - difficult task requiring a lot of work
hardware - task pertaining to hardware
help wanted - help is wanted for a task
invalid - something doesn't seem right or is not applicable 
medium - intermediate difficulty task requiring some significant
motion - anything relating to the locomotion of the robot
question - further information is requested
software - task pertaining software 
testing - task or feature that requires testing 
wontfix - this will not be worked
