### ISSUE TITLE
Cesar - Color Sensor Preliminary Testing

### ISSUE THREAD

**Issue by Zoom9000** [salamando15/TileBot#21]
Link to Arduino Framework:    https://github.com/arduino-libraries/Arduino_APDS9960
Header File : https://github.com/arduino-libraries/Arduino_APDS9960/blob/master/src/Arduino_APDS9960.h
C++ Program:  https://github.com/arduino-libraries/Arduino_APDS9960/blob/master/src/Arduino_APDS9960.cpp
- [x] - [x]  Review APDS 9960 Part and related engineering material/principles: 
    > I2C protocal software and hardware connectivity
    > Interrupts 
    > Schematic 
    > I/O pins 
    > Maximum Ratings vs Operating Characteristics 
    > IR LED 
    > Registerrs
- [x]  Connect wires between sensor, breadbaord, and raspberyy Pi. 
- [x]  Build a list of relevant/functional parameters
- [x] Convert C++ code from arduino framework to Python for communication and reading color sensing registers
- [x] Build basic infrastructure layer to check for ambient light, proximity, red, blue, green, and gesture readings
- [ ] Build a table that distinguishes the color readings

**Comment by ffund** [comment]
Since the code in 62202eb does not seem to get correct readings, we will try using the [Adafruit library](https://github.com/adafruit/Adafruit_CircuitPython_TCS34725).

Step 1:

```
sudo pip3 install adafruit-circuitpython-tcs34725
```

Step 2:

get report and run the example

```
git clone https://github.com/adafruit/Adafruit_CircuitPython_TCS34725
cd Adafruit_CircuitPython_TCS34725/examples
python3 tcs34725_simpletest.py
```

**Comment by ffund** [comment]
We tested with a few different colors and can definitely see the R/G/B value increase according to expectation.

Turquoise:
![image](https://user-images.githubusercontent.com/2316553/222206410-7a03488b-ee4c-4e5d-8493-5bac082c6871.png)

![image](https://user-images.githubusercontent.com/2316553/222205300-9e685adf-b905-46e2-a9e1-67e6590b42c0.png)


Red: 
![image](https://user-images.githubusercontent.com/2316553/222206317-f3d625b7-6e53-44fe-9436-3c0786b3534d.png)
![image](https://user-images.githubusercontent.com/2316553/222205483-4d2c7209-ed65-4d56-b861-6f81804f1c61.png)


Blue:
![image](https://user-images.githubusercontent.com/2316553/222206242-4affab95-8388-4fef-aeba-0dc966554ed0.png)
![image](https://user-images.githubusercontent.com/2316553/222205633-04e71505-8374-4389-81a0-6793bf16c13b.png)

Purple:
![image](https://user-images.githubusercontent.com/2316553/222206161-1231bec1-596c-4d22-92cc-ee7506f906a7.png)
![image](https://user-images.githubusercontent.com/2316553/222205832-8272bacc-c7cc-4dd0-8766-97674104748d.png)

**Comment by ffund** [comment]
Note: this was without interrupt pin.

**Comment by Zoom9000** [comment]
Red: (59,5,5) or (79,8,8)

white:  (14,18,14)


Blue: (16,16,16)  (9,16,25)
