### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by Zoom9000** [salamando15/TileBot#22]
After completing personas, draw out a wireframe prototype that outlines the physical interface of product and a browser based user interface:

- [ ]  Look up different board game covers and design 
- [ ]  Review what functions are better suited/available to users 
- [ ] Review how users may access the functions
- [x] Consult with manager about browser based user interface
- [ ] Create a board game cover sketch design
- [ ] Create a model that displays robot being built after parts assembled
- [ ] Sketch user interface with Tiles

**Comment by salamando15** [comment]
Created a wireframe for teacher portal using Balsamiq, 3/29/23



[TeacherDashboardWireframe.pdf](https://github.com/salamando15/TileBot/files/11098455/TeacherDashboardWireframe.pdf)
