### ISSUE TITLE
Schematic Color Sensor

### ISSUE THREAD

**Issue by CarlosLopezGit** [salamando15/TileBot#28]
- [ ] Create schematic for wiring the color sensor to the pi

**Comment by CarlosLopezGit** [comment]
@Zoom9000 could you upload a picture of your schematic

**Comment by Zoom9000** [comment]
[

![Image](https://user-images.githubusercontent.com/43012108/223711861-6087b430-bedd-4132-acc0-aeca8d1ea5d7.png)

](url)

**Comment by salamando15** [comment]
Reviewed and closed on team meeting 3/8/23
