### ISSUE TITLE
Scematic for RFID reader *

### ISSUE THREAD

**Issue by CarlosLopezGit** [salamando15/TileBot#29]
- [x] create schematic for wiring RFID reader to the pi

- Make sure there are no conflicts with existing schematics we made
- If a conflict arises contact the team member who's part conflicts and resolve conflict if possible, make note of this conflict in the comment for this issue

**Comment by CarlosLopezGit** [comment]
![Image](https://user-images.githubusercontent.com/47481629/223805300-63f63a89-8c03-418d-b6cf-bed7584dfe70.png)

**Comment by CarlosLopezGit** [comment]
change i2c bus to pins 2 and 3

**Comment by Zoom9000** [comment]
Tried to connect using I2C but no helpful resources were found online or practical implementations of I2C using the RFID 
Spoke to TA about implementing it in I2C but advised to use SPI 

![Image](https://user-images.githubusercontent.com/43012108/235032596-58c7c281-d0a9-4141-ac7b-7e736d39004d.png)
