### ISSUE TITLE
Schematic for for OLED

### ISSUE THREAD

**Issue by CarlosLopezGit** [salamando15/TileBot#31]
- [ ] created schematic for wiring OLED to pi

- make sure to avoid any wiring conflicts with other schematics
- if there conflicts make note of that in the comments under this issue and resolve if possible

**Comment by salamando15** [comment]
![Image](https://user-images.githubusercontent.com/22136782/223804444-eba2b274-32d7-434e-95fa-7cbabfa62fa6.jpg)

**Comment by CarlosLopezGit** [comment]
move i2c bus to to pins 2 and 3
